### ISSUE TITLE
Issue on windows with unzip

### ISSUE THREAD

**Issue by mrednic-1A** [buger/docs-mcp#7]
Hello,
I am trying to use this package an I have an issue with 'unzip' command, being on a Windows machine.
```
Error executing search_my_docs: MCP error -32601: Error executing docs search: Command failed: unzip -q "C:\Users\myuser\AppData\Local\npm-cache\_npx\c2487c62e2e543aa\node_modules\@buger\probe\bin\probe-v0.6.0-rc53-x86_64-pc-windows-msvc.zip" -d "C:\Users\myuser\AppData\Local\npm-cache\_npx\c2487c62e2e543aa\node_modules\@buger\probe\bin\temp_extract"
'unzip' is not recognized as an internal or external command,
operable program or batch file.
```
After I set up an unzip command for 7z I have errors related to the parameters of the command.
```
cmd: 'unzip -q "C:\Users\myuser\AppData\Local\npm-cache\_npx\c2487c62e2e543aa\node_modules\@buger\probe\bin\probe-v0.6.0-rc53-x86_64-pc-windows-msvc.zip" -d "C:\Users\myuser\AppData\Local\npm-cache\_npx\c2487c62e2e543aa\node_modules\@buger\probe\bin\temp_extract"',
2025-08-20 16:21:39.606 [warning] [server stderr] stdout: '',
2025-08-20 16:21:39.606 [warning] [server stderr] stderr: 'Command Line Error:  Unknown switch:-q'
```
The expected result will be that the 'unzip' to be not dependent on the OS.
And imo this is more related to the other package @buger/probe as that's the one unzipping and doing the search afterwards.

**Comment by buger** [comment]
I think should be fixed now

**Comment by mrednic-1A** [comment]
Hi @buger,
I think there is a problem with the publish(found some logs here: https://github.com/probelabs/docs-mcp/actions/runs/18448106247/job/52557718408) and the package is not anymore on npmjs. 

And I just tried the @probelabs/probe in my local and I guess I still have the error with unknown switch.
```
Error executing grep: MCP error MethodNotFound: Error executing grep: Grep function error: Command failed: unzip -q "C:\Users\myUser\AppData\Local\npm-cache\_npx\1e4d28c427a69c15\node_modules\@probelabs\probe\bin\probe-v0.6.0-rc128-x86_64-pc-windows-msvc.zip" -d "C:\Users\myUser\AppData\Local\npm-cache\_npx\1e4d28c427a69c15\node_modules\@probelabs\probe\bin\temp_extract"


Command Line Error:
Unknown switch:
-q
`````
